version: 2

general:
  branches:
    only:
      - master # list of branches to build
      - circleci-project-setup

jobs:

  test:
    docker:
      # specify the version
      - image: circleci/golang:1.12

    working_directory: /go/src/cinema-admin
    steps:
      - checkout

      - run: make setup-package
      - run: make test

  build:
    machine: true
    working_directory: /go/src/cinema-admin
    steps:
      - checkout

      # Build docker image
      # Push docker hub

      # specify any bash command here prefixed with `run: `
      - run: make setup-package
      - run: make build
  
  deploy: 
    # SSH server
    # Pull image
    # Run
    docker:
      # specify the version
      - image: circleci/golang:1.12

    working_directory: /go/src/cinema-admin
    steps:
      - checkout

      - run: make setup-package
      - run: make test

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      # - build:
      #     requires:
      #       - test
      # - deploy:
      #     requires:
      #       - build