jobs:

  test:
    docker:
      # specify the version
      - image: circleci/golang:1.12

    working_directory: /go/src/cinema-admin
    steps:
      - checkout

      - run: make setup-package
      - run: make test

  build:
    # branches:
      # only:
      # - master
      # - circleci-project-setup
      # - dev
    docker:
      # specify the version
      - image: circleci/golang:1.12

    working_directory: /go/src/cinema-admin
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: make setup-package
      - run: make build
  
  deploy: 
    # branches:
    #   only:
    #   - master
    #   - circleci-project-setup
    docker:
      # specify the version
      - image: circleci/golang:1.12

    working_directory: /go/src/cinema-admin
    steps:
      - checkout

      - run: make setup-package
      - run: make test

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deployment:
          requires:
            - build
      # - build
      # - deploy