version: 2

jobs:

  test:
    docker:
      # specify the version
      - image: circleci/golang:1.12

    working_directory: /go/src/cinema-admin
    steps:
      - checkout

      - run: make setup-package
      - run: make test

  build:
    # branches:
    #   only:
    #     - master
    working_directory: /go/src/cinema-admin
    docker:
      - image: docker:19.03.6-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run: docker build -t $IMAGE_NAME .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  
  deploy: 
    # SSH server
    # Pull image
    # Run
    branches:
      only:
        - master
    -working_directory: /go/src/cinema-admin
    steps:
      - checkout

      - run: make setup-package
      - run: make test

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      # - deploy:
      #     requires:
      #       - build