version: '3'
services:
  app:
    image: gitlab.umba.la:4567/umbala.tv/umbala.app/services/admin:release
    restart: always
    ports:
      - "9999:9999"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - POSTGREST_DB_HOST=103.56.156.165
      - POSTGREST_DB_PORT=5432
      - POSTGREST_DB_USER=postgres
      - POSTGREST_DB_PASSWORD=MPc3Uk4AMzyEeW1w4VlhrNlwCIWV2Q
      - POSTGREST_DB_NAME=donz
      - MAIN_REDIS_HOST=103.56.156.165
      - MAIN_REDIS_PORT=6379
      - CDN_SERVER_PRIVATE=https://cdn-vn-01.umba.la
      - CDN_SERVER_PUBLIC=https://cdn-vn-01.umba.la
      - CDN_ACCESS_TOKEN=k93c4G1j6vnEz0wB5Eo1m5o3uiJvIEvi
      - API_SERVER=https://gateway-vn-01.umba.la
      - API_KEY=asfsgVYIBKJkmlKNhbmlknklg