version: '3'
services:
  app:
    image: cinema-admin
    # restart: always
    container_name: cinema-admin_postgres
    ports:
      - "4000:4000"
    networks:
      - test_net

networks:
  test_net:
    driver: bridge
